### ISSUE TITLE
setpoint changes on its own

### ISSUE THREAD

**Issue by Aesculapius** [absalom-muc/MHI-AC-Ctrl#101]
I've been using the modules with succes for the last weeks. One apparent issue is that if I keep the modules behind the plastic, they get a too weak WiFi signal somehow and get stuck into some kind of loop. So they hang out of the unit, but that's fine with me.

On the unit downstairs I've notices for the second time now that the setpoint is changed to 33 degrees. It has been set to 24 degrees for the whole day and nothing has changed. The remote is stored into a drawer thus also cannot have been interfering. As you can see in the MQTT details, the setpoint as sent to the module is 24 degrees, but apparently it changed by itself to 33?

Not sure if this can be a software bug or whether it's a MHI ac bug. This is on a SRK-50ZSX-W

![image](https://user-images.githubusercontent.com/617061/184894690-a435d8d5-c169-4703-bbb5-1610acd0d84d.png)

![image](https://user-images.githubusercontent.com/617061/184894770-58cff7f4-ee1d-4431-875b-bda25b314b18.png)

Also not sure how to debug? It happend without apparent reason - was not fiddling around or adjusting any settings...

**Comment by Aesculapius** [comment]
Now that I look at my temperature graphs, I see that it has occurred more often on this unit. No issue on the other unit though...

![image](https://user-images.githubusercontent.com/617061/184899147-2bc23b56-cd60-42e1-aec3-b1bfd40baaf1.png)

**Comment by Aesculapius** [comment]
Yeah strange eh.
The AC indeed stops cooling as it feels no need to cool anymore (roomtemp is lower).
It is not automatically returned to the original value. At least, not the times that I noticed it. Needed to set the airco off and on again to have it reset the setpoint.
I've not seen it before 2.6R1. I'm happy to test with 2.5, but first want to see how reproduceable it actually is (hasn't occurred since posting this). Might try in a few days

**Comment by JoepWi** [comment]
I have the same issue with one of my units (MHI SRF25ZS-W) if set to heating. It raises the temperature on it's own. eg. Set to 22 and after a few seconds it's changed to eg. 24.
[logs_mhi-kantoor-joep_logs_problem.txt](https://github.com/absalom-muc/MHI-AC-Ctrl/files/9591419/logs_mhi-kantoor-joep_logs_problem.txt)
During the test above I had all HA automations disabled for this Airco unit.
The change of the target temperature is in my opinion coming from the MHI-AC-Ctrl unit.
Any help is welcome.

**Comment by joshuammex** [comment]
@JoepWi I have the same issue as yourself with a SETSRK25ZSA-W, and have since the get go. AC randomly increases the setpoint by 2c shortly after I manually set the temp. I'm running the [MHI-AC-Ctrl-ESPHome](https://github.com/ginkage/MHI-AC-Ctrl-ESPHome) fork.

**Comment by absalom-muc** [comment]
I don't know the HA implementation. What is displayed in the row
`[12:06:16][D][climate:414]:   Target Temperature: 22.00°C`?
It is the standard Tsetpoint (listed in the table in this [clause](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#mqtt-status)) or is it the [opdata](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#operating-data-mhi-ac-ctrl-coreh) Tsetpoint?
It is known that the opdata Tsetpoint is increased by 2°C for heating when AC is powered on and decreased when AC is powered off. This is a normal behaviour of the AC and has nothing to do with MHI-AC-Ctrl.
In general it is preferred when you provide the log from MHI-AC-Ctrl, not from an addon using it.

**Comment by JoepWi** [comment]
I traveling at the moment. Will look into it in a few weeks. Thanks for the explaination.

**Comment by hjkoster400d** [comment]
> I don't know the HA implementation. What is displayed in the row `[12:06:16][D][climate:414]: Target Temperature: 22.00°C`? It is the standard Tsetpoint (listed in the table in this [clause](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#mqtt-status)) or is it the [opdata](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#operating-data-mhi-ac-ctrl-coreh) Tsetpoint? It is known that the opdata Tsetpoint is increased by 2°C for heating when AC is powered on and decreased when AC is powered off. This is a normal behaviour of the AC and has nothing to do with MHI-AC-Ctrl. In general it is preferred when you provide the log from MHI-AC-Ctrl, not from an addon using it.
> 
> edit: The opdata 2 Tsepoint MQTT topic should be "SET-TEMP", not "Tsetpoint". This will be fixed in future.

Hi, 

Is the AC actually targeting a 2 degrees higher temp then was set? Would it be a valid assumption that when the AC is in heat mode, the targettemp set by the user is 2 degrees lower the AC is reporting?

Thanks for now,

Gr Rik

**Comment by absalom-muc** [comment]
> Hi,
> 
> Is the AC actually targeting a 2 degrees higher temp then was set? Would it be a valid assumption that when the AC is in heat mode, the targettemp set by the user is 2 degrees lower the AC is reporting?
> 
> Thanks for now,
> 
> Gr Rik

I don't think so, but I have no definite answer for you. IMO HA should use the standard Tsetpoint (listed in the table in this [clause](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#mqtt-status)) not the [opdata](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#operating-data-mhi-ac-ctrl-coreh) Tsetpoint. With the standard Tsetpoint there should be no increase of the value when heating.

**Comment by ervee** [comment]
> @JoepWi I have the same issue as yourself with a SETSRK25ZSA-W, and have since the get go. AC randomly increases the setpoint by 2c shortly after I manually set the temp. I'm running the [MHI-AC-Ctrl-ESPHome](https://github.com/ginkage/MHI-AC-Ctrl-ESPHome) fork.

I have the same with my split unit.  Also in the HA implementation. I did not see this during summer when cooling, but now with heating it likes to sometimes set the temperature +2 °C.

**Comment by JoepWi** [comment]
Below 3 screenshots from the ESPHome interface (no HA involved!):

**Start screen Airco OFF**
![Schermafbeelding 2022-10-03 om 10 59 43](https://user-images.githubusercontent.com/87470267/193542300-88a5add7-8ce4-48aa-a3c4-8a3c3eea35e6.png)

**Airco manual on this webpage set to HEAT**
![Schermafbeelding 2022-10-03 om 11 00 18](https://user-images.githubusercontent.com/87470267/193542315-96f287bb-8351-4a3c-b1a5-0b99f11b4009.png)

**When the fan of the indoor units starts blowing the temp increases 2 degrees**
![Schermafbeelding 2022-10-03 om 11 00 48](https://user-images.githubusercontent.com/87470267/193542323-0ba739db-4eb5-4ef1-bb4c-d359412c34d9.png)

I have this issue with all 4 indoor units I have.

**Comment by JoepWi** [comment]
Nobody any idea?

**Comment by ervee** [comment]
I just used my AC to heat. In HA it was off and set temp was 21C. I powered on the AC with the iR remote set to 21C. When I wanted to switch the AC off with HA I saw it set on 23C again but when I pressed the off button the set temp immediately went back to 21. So perhaps it is just cosmetic? And I see absalon-muc mention something about the Tsetpoint usage for the HA implementation being incorrect. Perhaps @ginkage can say something about this.
It could well be that the AC sets its internal setpoint to +2°C because of warm air rising to the top mounted sensor...

PS this perhaps has nothing to do with the original post. His temperature increases it a bit more than 2°C.

**Comment by mikeschenkel** [comment]
This behavior has nothing to do with the MHI-AC-Ctrl software. An offset of 2°C in heating operation is determined by the AC itself. You can turn this off by holding down the ON/OFF button on the AC for 30 seconds while in heating operation. After you hear a beep and set a new temperature with the remote the offset should be resolved.

![countermeasure-for-excessive-temperature-rise](https://user-images.githubusercontent.com/7232346/198034613-6e813d3e-a21e-455d-8f4d-56465a8467c8.jpg)

**Comment by Aesculapius** [comment]
Haven't had troubles for a while but now, in the heating season, the issue seems to return. Now I'm seeing it on the tRoom value.

I'm setting the temp via mqtt every 20 seconds via /set/Troom:
![image](https://user-images.githubusercontent.com/617061/198220215-77f25926-cd23-4fad-92f8-e18a7a413a74.png)

but still the units own tRoom in /Troom keeps changing to other values now and then (plus 2,5 degree):
![image](https://user-images.githubusercontent.com/617061/198220265-39ebe2b7-2665-400b-9533-b471c44c5226.png)

Seems to be a similar problem, not sure what to do next. Other thing is that at once I also have strange fSCK values (and thus the unit cannot be controlled also). Might be connected. I'll have to power-cycle everything to get it working again...
![image](https://user-images.githubusercontent.com/617061/198220578-1a0ba241-7012-49ff-9ab1-6ca440abeac7.png)

**Comment by tomm1ed** [comment]
> Haven't had troubles for a while but now, in the heating season, the issue seems to return. Now I'm seeing it on the tRoom value.
> 
> I'm setting the temp via mqtt every 20 seconds via /set/Troom: ![image](https://user-images.githubusercontent.com/617061/198220215-77f25926-cd23-4fad-92f8-e18a7a413a74.png)
> 
> but still the units own tRoom in /Troom keeps changing to other values now and then (plus 2,5 degree): ![image](https://user-images.githubusercontent.com/617061/198220265-39ebe2b7-2665-400b-9533-b471c44c5226.png)
> 
> Seems to be a similar problem, not sure what to do next. Other thing is that at once I also have strange fSCK values (and thus the unit cannot be controlled also). Might be connected. I'll have to power-cycle everything to get it working again... ![image](https://user-images.githubusercontent.com/617061/198220578-1a0ba241-7012-49ff-9ab1-6ca440abeac7.png) ![image](https://user-images.githubusercontent.com/617061/198220754-6a40e60a-e1a9-4e21-ad36-d6e7072347ec.png) ![image](https://user-images.githubusercontent.com/617061/198220845-8c9d6fe5-151c-4d7b-a897-ec4cde533e60.png)

I am having similar issues:
https://github.com/absalom-muc/MHI-AC-Ctrl/issues/105
Maybe you can add to that issue? (since your Tsetpoint issue has been resolved maybe also close this issue?)

**Comment by absalom-muc** [comment]
> This behavior has nothing to do with the MHI-AC-Ctrl software. An offset of 2°C in heating operation is determined by the AC itself. You can turn this off by holding down the ON/OFF button on the AC for 30 seconds while in heating operation. After you hear a beep and set a new temperature with the remote the offset should be resolved.
> 
> ![countermeasure-for-excessive-temperature-rise](https://user-images.githubusercontent.com/7232346/198034613-6e813d3e-a21e-455d-8f4d-56465a8467c8.jpg)

Thank you @mikeschenkel , I've seen a lot of different manuals for the AC, but never noticed that the 2°C offset was addressed.

**Comment by Aesculapius** [comment]
> Haven't had troubles for a while but now, in the heating season, the issue seems to return. Now I'm seeing it on the tRoom value.
> 
> I'm setting the temp via mqtt every 20 seconds via /set/Troom: ![image](https://user-images.githubusercontent.com/617061/198220215-77f25926-cd23-4fad-92f8-e18a7a413a74.png)
> 
> but still the units own tRoom in /Troom keeps changing to other values now and then (plus 2,5 degree): ![image](https://user-images.githubusercontent.com/617061/198220265-39ebe2b7-2665-400b-9533-b471c44c5226.png)
> 
> Seems to be a similar problem, not sure what to do next. Other thing is that at once I also have strange fSCK values (and thus the unit cannot be controlled also). Might be connected. I'll have to power-cycle everything to get it working again... ![image](https://user-images.githubusercontent.com/617061/198220578-1a0ba241-7012-49ff-9ab1-6ca440abeac7.png) ![image](https://user-images.githubusercontent.com/617061/198220754-6a40e60a-e1a9-4e21-ad36-d6e7072347ec.png) ![image](https://user-images.githubusercontent.com/617061/198220845-8c9d6fe5-151c-4d7b-a897-ec4cde533e60.png)

As for my issue with strange SCK value (0), this was caused by a not infinite resistance between the pins of C2. Looked like some kind of corrosion. After cleaning that up and scraping off residue, everything worked again as intended. 

I also changed the ROOM_TEMP_MQTT_SET_TIMEOUT interval to 90 as per https://github.com/absalom-muc/MHI-AC-Ctrl/issues/105#issuecomment-1295017726 which seems to work so far...

**Comment by tomm1ed** [comment]
> This behavior has nothing to do with the MHI-AC-Ctrl software. An offset of 2°C in heating operation is determined by the AC itself. You can turn this off by holding down the ON/OFF button on the AC for 30 seconds while in heating operation. After you hear a beep and set a new temperature with the remote the offset should be resolved.
> 
> ![countermeasure-for-excessive-temperature-rise](https://user-images.githubusercontent.com/7232346/198034613-6e813d3e-a21e-455d-8f4d-56465a8467c8.jpg)

Does this actually work for anyone? Tried this 3 times but no bibibi sound from my SRK 35 ZSX and the machine goes full blast when it turns on. The temperature is 18.9 at the external temp sensor which is translated to 18.5 on the MHI-AC-CTRL and at the lowest setting of 18 this means the unit tries to heat until it’s 20 thinking it has a delta of 1.5 degrees. Very loud and very high usage is the result so I would like to fix this by following this manual. can anyone explain exactly how to do this?

**Comment by buennerbernd** [comment]
Have you tried eco-mode and silent-mode?
I would assume this saves some energy.

**Comment by tomm1ed** [comment]
> Have you tried eco-mode and silent-mode? I would assume this saves some energy.

I have not and I don't intend to ;) I want my Airco to use the correct Setpoint and not Setpoint +2. Of this option does not work with the ZSX I will just feed it TRoom+1 or +2 but would prefer to use correct values.

**Comment by tomm1ed** [comment]
> > This behavior has nothing to do with the MHI-AC-Ctrl software. An offset of 2°C in heating operation is determined by the AC itself. You can turn this off by holding down the ON/OFF button on the AC for 30 seconds while in heating operation. After you hear a beep and set a new temperature with the remote the offset should be resolved.
> > ![countermeasure-for-excessive-temperature-rise](https://user-images.githubusercontent.com/7232346/198034613-6e813d3e-a21e-455d-8f4d-56465a8467c8.jpg)
> 
> Does this actually work for anyone? Tried this 3 times but no bibibi sound from my SRK 35 ZSX and the machine goes full blast when it turns on. The temperature is 18.9 at the external temp sensor which is translated to 18.5 on the MHI-AC-CTRL and at the lowest setting of 18 this means the unit tries to heat until it’s 20 thinking it has a delta of 1.5 degrees. Very loud and very high usage is the result so I would like to fix this by following this manual. Could anyone please explain to me exactly how to do this? @mikeschenkel maybe ?
> 
> ![](https://camo.githubusercontent.com/41eb978d28e2103ba8648c18ad6f7b10cd3a9454d8234fc8c0a2fd6f0e156128/68747470733a2f2f747765616b6572732e6e65742f666f746f616c62756d2f696d6167652f574569663159433350423573304252596741765a4d4157332e706e67)

Too be 100% sure, they are talking about the On/Off button on the Remote yes? (@mikeschenkel )

**Comment by mikeschenkel** [comment]
@tomm1ed No, you they're talking about the physical ON/OFF button on the AC unit itself.

**Comment by tomm1ed** [comment]
> @tomm1ed No, you have to hold down the physical ON/OFF button on the indoor AC unit itself.

Thank you you are a life saver :) Held it for over 30 secs and bipbip it works 👍

**Comment by buennerbernd** [comment]
I have tested this too. 
In eco mode the new behavior is: OpData/Tsetpoint = Tsetpoint - 1
Without eco mode: OpData/Tsetpoint = Tsetpoint

**Comment by Aesculapius** [comment]
As per my comment on 2nd of November, this issue hasn't occurred and I feel it was related to both that setting as my local hassle with corrosion on the pcb. The posts after that discuss a different topic so maybe should be split and this one closed?
