### ISSUE TITLE
ESP32 - D1 Mini Pro

### ISSUE THREAD

**Issue by sanderlv** [absalom-muc/MHI-AC-Ctrl#107]
Hi, please may I also ask here:

https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/issues/43

_Hi, I have tried to use a D1 Mini Pro ESP32 instead of an ESP8266. But to no avail, it just wont boot.

I want to use the advantage of also using the new bluetooth proxy component in the ESP32.

Is there any hard coding towards ESP8266?

Is it possible to use an ESP32?

board type: wemos_d1_mini32_

**Comment by absalom-muc** [comment]
Beside the pin defintions I'm not aware of ESP8266 specifics in MHI-AC-Ctrl program.

**Comment by sanderlv** [comment]
My experience with esphome is that for d1 mini (8266) I need to use "d1, d2, etc." as pin layout number. As for esp32 I use "GPIO1, GPIO2, or just a number like 1, 2, etc.).

**Comment by hjkoster400d** [comment]
Nice that you are trying this on the ESP32, i was also thinking about that. Please let me know if you get it to work, and which modifications to get it compatible.

**Comment by sanderlv** [comment]
The other way around too. If you find out. let me know/

**Comment by absalom-muc** [comment]
I believe this topic was already solved [here](https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/issues/43) -> closed
