### ISSUE TITLE
Wrong assembly orientation of X1 in KiCad PCB layout

### ISSUE THREAD

**Issue by absalom-muc** [absalom-muc/MHI-AC-Ctrl#111]
@oliv3r : Not sure if you have seen my question in your [KiCad pull request](https://github.com/absalom-muc/MHI-AC-Ctrl/pull/106).

![grafik](https://user-images.githubusercontent.com/23119513/200112913-9e975542-9748-4d92-90d3-2e2f3bef2e5a.png)

 I believe the orientation of X1 is not correct and should be rotated by 180°. Could you recheck?

**Comment by oliv3r** [comment]
Hey @absalom-muc,

don't think so? I took this picture of you as reference: 
![image](https://user-images.githubusercontent.com/1245341/200554673-7061508d-b942-419a-9e55-18b06a8098d0.png) obviously this is the male mounted at the bottom, but the 'tabs' are pointing the same way, board-inside. I agree that the actual connector is on the wrong side and uses the wrong model :p but that shouldn't matter?

Looking at the pcblayout: 
![image](https://user-images.githubusercontent.com/1245341/200554903-216eecba-bfd1-44b0-80f1-fd034dbe1ed8.png)
GND is pin 1 facing the 'middle' +12V is the bottom one facing the edge. As I 'traced' your PCB, I'm fairly confident that the pin orientation is identical to yours?

So pins are GND, MISO, MOSI, CLK, 12V which is exactly what you had as well (though no silkscreen helpers on those labels :p)

**Comment by oliv3r** [comment]
Well right now the connector is just a render, and the pinout matches exactly that of a female (the housing is male?) on the bottom. So if you'd solder this board, and put the correct connector on the bottom with the edges facing inwards, your fine.

If I 'flip' the connector to the bottom, it _looks_ like this: 
![image](https://user-images.githubusercontent.com/1245341/200844813-bce782cf-de7b-48e8-822a-146337d53935.png)

But regardless, the pinout stays completly _identical_. So in the end, it's just how the component is being rendered. I do agree it makes logically more sense :p to at least show it exactly as you'd have to assemble it with extension cable type A). But I'm sure excention cable type B exists just as much, which makes it work with the current rendering. Caveat emptor I would say. I'll open a MR with the correct _rendering_ of the connector. But note, that ultimately, the PCB gerber is still the same as before!

**Comment by oliv3r** [comment]
https://github.com/absalom-muc/MHI-AC-Ctrl/pull/113

**Comment by absalom-muc** [comment]
I understand that the gerber is unchanged and that only the rendering is affected. But I've also seen in the last years that for unexperienced users this minor "inconsistency" creates confusion. Would it be possible to make a female connector and to rotate it by 180°? Then we are consistent to the existing assembly pictures. Thank you.

**Comment by oliv3r** [comment]
> Then we are consistent to the existing assembly pictures
I'd have to do some 3D modelling to create that connector :), which is not something I've done before much. So that's certainly a challenge :) So #113 puts it on the correct side, the 180degree rotation would then only be applicable because it's a female header. I'll see what I can do on those rendering skills. We could also omit the render of the connector for the time being :p

**Comment by absalom-muc** [comment]
Thank you for your efforts @oliv3r
