### ISSUE TITLE
[Feature request] Adding offset for external temperature sensor

### ISSUE THREAD

**Issue by glsf91** [absalom-muc/MHI-AC-Ctrl#119]
I have an an external temperature sensor (DS18B20) connected. Depending on the place where it is mounted it has an offset with the "real" room temperature. Also because of the resolution of 0,5 degrees that can make the difference between too hot or too cold.

It should be nice if we can specify an offset (with resolution ,1 degree) for the measured temperature.
This can be defined in support.h or make it more flexible by adding a MQTT topic which can be set.
To make it more flexible it can also be used for Troom (but not my use case).
Maybe also adding to check if the offset lies for example between -5 and +5 degrees.

I don't use any automation to set things. I just use MHI-AC-Ctrl als replacement for the internal temp sensor.
This feature make it possible to use a setpoint with the remote control which is "real" instead of (de)(i)ncreasing it with 1 or 2 degrees.  Increasing also the WAF

**Comment by absalom-muc** [comment]
Added to v2.6R5
