### ISSUE TITLE
SSL eventually? 

### ISSUE THREAD

**Issue by ligangyi** [absalom-muc/MHI-AC-Ctrl#12]
Have this working on my home network, I was gonna implement SSL on my MQTT broker (Mosquitto), but then I realised as of now, there's no option to support SSL for this project.

**Comment by absalom-muc** [comment]
MHI-AC-Ctrl and Mosquitto support SSL, what is the problem?

**Comment by ligangyi** [comment]
MHI-AC-Ctrl now implements a plaintext password. TLS/SSL encrypts data transmission and uses port 8883.

**Comment by absalom-muc** [comment]
O.k., I see your point. Currently I have not planned to implement SSL/TLS, because I don't use it. When you are interested to add it, the [MQTT client](https://github.com/knolleary/pubsubclient) might be a good starting point. There were some discussions related to TLS/SSL.
