### ISSUE TITLE
Question: outdoor fanspeed always high at low temperature

### ISSUE THREAD

**Issue by lwestenberg** [absalom-muc/MHI-AC-Ctrl#133]
Perhaps not really the place to ask as it is not a bug or something in the MHI-AC-Ctrl code but hopefully someone can answer my question here:

Does anybody experience that around 0 degrees or lower the outdoor fan always goes to 8 (max) and stays there. This happens here even when the inside temperature is reached and outdoor humidity is low. Compressor freq is about 28-30.

Model: MHI SRK 50-ZS-W (equipped with ESP running MHI-AC-Ctrl)

**Comment by synegic** [comment]
Have you tried simply using the remote on 'normal' settings? E.g. not using the silent or auto mode? I can imagine the unit in general just needs to work harder (move more air through the radiator) to get that last little bit of energy out of the air at temps around 0 degrees. There is not much MHI-AC Ctrl can do about that; outside unit fan speed is determined by the AC itself.

**Comment by DanDee127** [comment]
When the outdoor air temperature (models SRK20, 25, 35 : TH3 ; models SRK50, 60 : TH2) is -2°C (models SRK50, 60: 4°C) or lower continues for 30 seconds while the compressor speed is other than 0 rps.

The outdoor fan is stepped up by 2 speed step at each 20 seconds. (Upper limit 8th speed)

Reset conditions
When either of the following conditions is satisfied.
a)The outdoor air temperature (models SRK20, 25, 35 : TH3 ; models SRK50, 60 : TH2) is 0°C
(models SRK50, 60: 6°C) or higher.
b)The compressor speed is 0 rps.

**Comment by lwestenberg** [comment]
Wow @DanDee127 thanks for the explanation!

**Comment by glsf91** [comment]
@lwestenberg If it is solved please close the issue

**Comment by lwestenberg** [comment]
Solved, thanks
