### ISSUE TITLE
Addition to unsupported list

### ISSUE THREAD

**Issue by zenstrukt** [absalom-muc/MHI-AC-Ctrl#143]
Providing feedback for the unsupported list. It appears my **SRK71ZEA-S1** does not support the output required. My PCB per the below...

![image](https://user-images.githubusercontent.com/18431572/231110884-0a829d7f-dd6e-474c-9779-feb17ec47f30.jpeg)

Unless there's something I'm missing here...

**Comment by henrykuijpers** [comment]
Cns is there, but it still needs to be soldered. If you do that, you should be able to use mhi-ac-ctrl.

**Comment by absalom-muc** [comment]
> Cns is there, but it still needs to be soldered. If you do that, you should be able to use mhi-ac-ctrl.

Are you sure @henrykuijpers ? The CNS connector of the SRK71ZEA-S1 has 6 pins, but I'm only aware of 5-pin-CNS connectors.

**Comment by glsf91** [comment]
Added to not supported list in pull request https://github.com/absalom-muc/MHI-AC-Ctrl/pull/145
Let me know if I have to undo this.

**Comment by absalom-muc** [comment]
Thank you for your feedback @zenstrukt

**Comment by sb180276** [comment]
I'm hoping it's possible to solder the 5 connections from the MHI-AC-Ctrl board, to 5 of the 6 pin CNS on the SRK71ZEA-S1.  
Anyone found the pinouts?
