### ISSUE TITLE
Remote Control Timer does not work anymore

### ISSUE THREAD

**Issue by HeadCrash66** [absalom-muc/MHI-AC-Ctrl#148]
Hi,

with an older version (< 2.6) I was able to use my IR remotes to set an power off timer (or sleep timer).
With the latest version this does not work anymore. The AC stays on.

Is this normal? I would prefer to have the RC timer working again, is there an ootion I may have missed?

Thanks for any suggestions.

**Comment by glsf91** [comment]
That is normal. Also when the official WF-RAC module is connected this is not working anymore.
