### ISSUE TITLE
I request that the SRK xx ZSPR-S model be moved to the list of supported models

### ISSUE THREAD

**Issue by AlexzeyK** [absalom-muc/MHI-AC-Ctrl#149]
I saw your project and got interested in it.
I ordered boards and parts and assembled a few pieces.
I was not attentive. I didn't read the list of unsupported models. I started programming modules and saw that my model is not supported.... I have 4 of these models. I continued anyway... When I finished installing the module, I could not believe my eyes: my SRK 63 ZSPR-S model works.
I request that the SRK xx ZSPR-S model be moved to the list of supported models.
The photo shows the model, the board with the installed CNS connector and the MKTT topics.
I'm glad everything works.
Thank you very much for your work!!!
![20221102_150914](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/77577796/eade32f0-eb71-4c5a-beb1-caefb481add0)
![20221102_151008](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/77577796/47be77e5-6084-40cb-8748-bb403c189373)
![20221102_152042](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/77577796/98da3421-3a20-4a6e-a891-da9ecffc886f)
![20221102_153648](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/77577796/a02c0aba-7d9f-4942-b32f-95778f67a42d)
![20221102_160521](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/77577796/420e36b3-3229-4682-95e5-88a03844bb58)
![261](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/77577796/81194531-da1f-4df6-9e33-34d8aca12e0b)
![262](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/77577796/6a433762-0ebd-415c-92df-5d0186ae77f4)

**Comment by absalom-muc** [comment]
Thanks for your feedback @AlexzeyK 
Added your AC to the list of supported models.
