### ISSUE TITLE
[Feature request] Air Flow

### ISSUE THREAD

**Issue by Kitser** [absalom-muc/MHI-AC-Ctrl#153]
Firstly thank you for the great work 👍🏻🙏
It would be great to control the air flow. So left/right and up/down.
I hope this is possible.

**Comment by glsf91** [comment]
Up/down is already working. left/right is not possible without a major change. See also #77

**Comment by Kitser** [comment]
Up/down is only the up/down swing. I mean all the up/down directions.

**Comment by glsf91** [comment]
No, not only swing. For up/down 4 positions are possible. Like in de smart m-air app.
(RC has an extra up/down position (45 degrees) which is also not in de app)

**Comment by Kitser** [comment]
I'm using the Esphome fork. And i needed to update my devices for the up/down function. Thanks!
