### ISSUE TITLE
Addition to unsupported list

### ISSUE THREAD

**Issue by sergioperez** [absalom-muc/MHI-AC-Ctrl#154]
I have a SRK35ZC-S board, which has a 6 pin CNS connector, as it happens with #143 

genik from the Home Assistant forum reports to also have found the same connector: https://community.home-assistant.io/t/mitsubishi-air-conditioner-remote-control/20753/19

![imagen](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/805463/70761b7b-cb68-4105-b44d-2f70e21ea97f)

**Comment by glsf91** [comment]
Added to unsupported list
