### ISSUE TITLE
How to use MQTT_PREFIX HOSTNAME?

### ISSUE THREAD

**Issue by testkandidat** [absalom-muc/MHI-AC-Ctrl#156]
Hello,

i set #define MQTT_PREFIX HOSTNAME "/ac_dg" and i am not sure how the resulting publishing path looks like after setting this option.

**Comment by absalom-muc** [comment]
Assumed that HOSTNAME is still "MHI-AC-Ctrl" then it will be "MHI-AC-Ctrl/ac_dg"

You could also just test it e.g. by using the [MQTT Explorer](http://mqtt-explorer.com/)

**Comment by glsf91** [comment]
I assume solved. I will close this one
