### ISSUE TITLE
Unable to send commands to the MHI-AC-Ctrl

### ISSUE THREAD

**Issue by Allinijhof** [absalom-muc/MHI-AC-Ctrl#165]
Name of my AC: SRK 35 ZS-W
Used MHI-AC-Ctrl HW: ESP8266 ((WEMOS D1 R2 & mini with 160 MHz)
Used MHI-AC-Ctrl SW: MHI-AC-Ctrl-2.8

I am able to connect the MHI-AC-Ctrl to my aircon, OpData has been displayed successful, updates have been processed through MQTT (ie RETURN-AIR). Unfortunately I am not able to send commands to the MHI-AC-Ctrl. 

Could you please advise what I have to do to send ie Power on to my device?

How can I send other commands like Mode Cool to the device?

Many thanks for your support!

Regards,
Allard

[MHI-AC-Ctrl.zip](https://github.com/absalom-muc/MHI-AC-Ctrl/files/13404596/MHI-AC-Ctrl.zip)

**Comment by absalom-muc** [comment]
Have you checked cmd_received (see [here](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#mqtt-status))?
If you see no reaction on cmd_received then you use the wrong set-topic or something goes wrong with the connection of the MISO signal between ESP8266 board and your AC.

**Comment by Allinijhof** [comment]
Hi Absalom,

I have received cmd_received = "unknown command"

**Comment by absalom-muc** [comment]
Very good, use e.g. MQTT-Explorer to check the set topic, then you should see what is wrong with your commands. E.g. when switching mode to Cool you should see
![grafik](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/23119513/68d675d0-b5f9-4e90-a1e9-0408ecec9c94)

**Comment by Allinijhof** [comment]
Hi Absalom, 

I have been reverting the HOSTNAME to default = 'MHI-AC-Ctrl", after sending the command to topic = MHI-AC-Ctrl/set/Power and with message = On the airco started to work.

Apparently the HOSTNAME hasn't been updated everywhere... I changed HOSTNAME in Support.h, where did I miss the update when I wanted to make the controller room specific?

**Comment by absalom-muc** [comment]
It should be sufficient changing HOSTNAME only. Maybe recheck upper/lowercase of your changed HOSTNAME

**Comment by Allinijhof** [comment]
Spot-on! Thanks four your support!

**Comment by glsf91** [comment]
I close this one because it is solved.
