### ISSUE TITLE
KiCAD: J1 Connector pinout is wrong

### ISSUE THREAD

**Issue by AlexCPU** [absalom-muc/MHI-AC-Ctrl#167]
The KiCAD design was "fixed" in #155 to model a female connector correctly on the reverse of the board, which involved flipping the connector.  However the schematic wasn't updated, so the PCB layout has the pins defined incorrectly:
![image](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/4178651/a22731c1-aa98-4e68-9a5a-76109e68b589)
You can see the unconnected nets, and the fact that different named nets are connected to the pins (easiest to see on the GND and +12V pins).
I'll see if I can raise a PR for this.

Unrelated question: I'm making a new version of the board with an ESP32-C3 integrated (i.e. no extra D1 Mini) with mostly SMD parts, any preference in the repo where to put it?

**Comment by glsf91** [comment]
That epshome fork is using a part of the mhi-ac-ctrl code.
I have also tried with that esphome fork without success.
So I suggest you first trying to get this up and running without errors before making a new version of the board :-)

**Comment by oliv3r** [comment]
Sorry for not noticing this !! Thanks @AlexCPU for the fix :)
