### ISSUE TITLE
AC Controller with touch display with ESP32 integrated

### ISSUE THREAD

**Issue by glsf91** [absalom-muc/MHI-AC-Ctrl#173]
I have created a AC controller which works with MHI-AC-Ctrl by using MQTT.
![image1](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/33393611/49aa5c83-cfa9-465f-bf07-c59b6e9ab892)

Details are on https://github.com/glsf91/MHI-AC-Ctrl-AC_controller/tree/main

**Comment by absalom-muc** [comment]
Looks great!

**Comment by glsf91** [comment]
Added to Integration list.
