### ISSUE TITLE
How to "flash" after adding files in ESPhome

### ISSUE THREAD

**Issue by elrosso2** [absalom-muc/MHI-AC-Ctrl#178]
Is there a "How to" for flashing this MHI-AC-CTRL file? I can not find anything on the internet how it should be flashed.

Thanks for the help.

**Comment by glsf91** [comment]
This is not the esphome repo so you question does not belong here.
But you have to do it like every normal ESPhome software is [flashed](https://esphome.io/guides/getting_started_command_line)

**Comment by glsf91** [comment]
I see you also asked the question in the ginkage repo which is the right place. 
I will close this one.
