### ISSUE TITLE
Model SRK 25 ZSPR-S is not supported

### ISSUE THREAD

**Issue by vokamut** [absalom-muc/MHI-AC-Ctrl#185]
There is no connector on the board, which is a pity(
![20240412_134039](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/4266448/d346bdee-481b-4462-938a-fdefb5fe8592)

**Comment by glsf91** [comment]
That's too bad. Thanks for letting this know.
I added your model to the unsupported list and closed this issue.

**Comment by pavelgyravel** [comment]
Same for SRK20ZSPR-S 
![image](https://github.com/user-attachments/assets/c50d20d1-bdb6-4737-9d3e-821b743b2b05)
![image](https://github.com/user-attachments/assets/74989b7d-8b36-4f19-93e8-90f23f24f509)
