### ISSUE TITLE
Can't send data to the ac "SRK20ZS-W"

### ISSUE THREAD

**Issue by leMax6608** [absalom-muc/MHI-AC-Ctrl#186]
**To Reproduce**
Name of my AC: SRK20ZS-W
Used MHI-AC-Ctrl HW: Wemos D1 Mini from AZDelivery
Used MHI-AC-Ctrl SW: 2.8

**Describe the bug**
Hello. Today I tried to make thze climate control with a wemos d1 mini. The data from the ac is showed in IOBroker but I just can't figure out how to send data. Everything I tried failed. 
![Screenshot 2024-05-04 221014](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/104273250/9cf2c78e-86c7-4de5-b6d6-3dbcd5a3a3c1)
![HA](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/104273250/314f618d-05f2-4033-82e5-8f760186e18a)
![IMG_0096](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/104273250/85827302-c3e4-4248-b5fa-6e6a76009c65)
![IMG_0098](https://github.com/absalom-muc/MHI-AC-Ctrl/assets/104273250/e30b6ac2-a672-480c-887f-7f76c0fd3f55)
There are pictures of my MQTT cofiguration and the installation in the ac.

Can you please help me fixing this problem?

**Comment by absalom-muc** [comment]
What is your configuration for
`MQTT_SET_PREFIX MQTT_PREFIX` ?
Per default it is "set/", not "Set/"

**Comment by leMax6608** [comment]
I think you‘re right. I will try it this evening and let you know if it works.

**Comment by leMax6608** [comment]
Hi. I tried it and just the /set/Power won‘t work. But when I enabled Power On when changing Modes, it suddenly works. I think I will do a YT Video on how to do this whole process and set it up with home assistant.

**Comment by absalom-muc** [comment]
Thanks for the feedback
