### ISSUE TITLE
Support for SRK13CHV?

### ISSUE THREAD

**Issue by ferbulous** [absalom-muc/MHI-AC-Ctrl#194]
Hi, not a bug
I have a question regarding the CNS port 
For my MHI (SRK13CHV-4), that port isn’t listed in the diagram and I couldn’t remove the pcb without some downtime

![IMG_4165](https://github.com/user-attachments/assets/0ee5d708-dfe0-4579-8151-c59a8218a57f)
![IMG_4163](https://github.com/user-attachments/assets/9a898503-6626-46cc-a62c-6818b9544e36)

I googled the model number instead and apparently there’s CNS labeled with no JST connector

![IMG_4511](https://github.com/user-attachments/assets/4172a5c9-d77f-4db7-bb43-06cfdefa42a5)

Am i correct to assume that port is still functioning and all I need to do is just solder JST connector to it?

**Comment by glsf91** [comment]
Only somebody with the same unit and did the same can tell you.
There will be a reason the connector is not there. But you can give it a try.

**Comment by ferbulous** [comment]
Just noticed this post here where the pins just need to be soldered

https://github.com/absalom-muc/MHI-AC-Ctrl/issues/143#issuecomment-1510408359

Unfortunately it looks like my unit has 6 pins instead of 5

**Comment by Dennisjvdb** [comment]
Would it be possible to design a PCB with a 6 pin connector? So the models with CNE port or 6pin CNS port can also be supported?

**Comment by ferbulous** [comment]
I'd say the better question is if we could send a replacement pcb with a 6 cns pin to the dev @absalom-muc  if he could work with that.

**Comment by Dennisjvdb** [comment]
I think al models have a 6-pin cne connector. Might be better as no soldering would be required.

**Comment by absalom-muc** [comment]
When my understanding is correct we don't know the technical differences between the 5 and 6-pin connector, e.g.

1. Can the 6-pin connector be used for a remote control? (someone could check if there exists a commercial available remote control for this.)
2. What is the protocol used for the 6-pin connector? (could be also MHI-SPI-Ctrl's SPI, or could be completely different)
3. If it is SPI what is the purpose of the 6th pin and what is the assignment of the other pins

btw: I don't plan adaption for a 6-pin version

**Comment by Dennisjvdb** [comment]
In [this](https://github.com/dvisser/MHI-ESP-PCB) project, the CNE connection is used for added features. So, I think it can be used for remote control. I'm not sure what the protocol is, as I have a limited understanding of these protocols. If the same protocol is used and we know the pin assignment, would it theoretically be possible to connect this module to a 6-pin male connector without using the 6th pin?

**Comment by absalom-muc** [comment]
[Here](https://github.com/dvisser/MHI-ESP-PCB/blob/main/Images/Module%20-%20Top.jpg), I see only a 5-pin connector. Can't see if it is the usual 5-pin CNS or something different.
And I can't find an accessable schematic (I don't use Kikad)

**Comment by Dennisjvdb** [comment]
I think [this](https://github.com/dvisser/MHI-ESP-PCB/blob/main/MHI%20ESP.pdf) the schematic in pdf.

**Comment by absalom-muc** [comment]
Ah, o.k., but no support of 6-pin:
![grafik](https://github.com/user-attachments/assets/a9bc15e9-95c4-4333-bce6-bcadb799bcd6)

**Comment by glsf91** [comment]
I think we can close this one. Otherwise I can reopen it if needed.
