### ISSUE TITLE
Disassemble the air conditioner

### ISSUE THREAD

**Issue by aleksandrdobrynin** [absalom-muc/MHI-AC-Ctrl#20]
Hey.
Tell me how to disassemble the air conditioner, I can not find any instructions. Ideally, some screenshots of what to unscrew and how to get to the CNS port can.
SRK 25ZS-S

**Comment by absalom-muc** [comment]
Have a look on [this](http://downloads.klimacorner.de/dateien/Technisches_Handbuch_S-Serie.pdf). It is the German language version, but the illustrations could help.

**Comment by aleksandrdobrynin** [comment]
Thank. I found the manual and took it apart. I ordered the details, on Monday I have to bring it and I will collect it. I did not find the board itself where I can make it, I'll try to assemble it without it: /
