### ISSUE TITLE
Add DXK24ZMA-S as supported

### ISSUE THREAD

**Issue by unregist** [absalom-muc/MHI-AC-Ctrl#201]
I've successfully got it working on DXK24ZMA-S (presumably working on all DXK xx ZMA-S)
Do note I am using ESP32 and the ESPHome fork of this project, but that should not make a difference.
I changed the GPIO to CLK 21 MISO 22 MOSI 23

I did however get a occasional -4 error, they disappeared by changing the maximum loop time to 200ms (It probably works with a bit less but I didn't bother testing at which point it breaks). Could also be caused by my hardware rather than the device.

**Comment by glsf91** [comment]
Thanks. Done
