### ISSUE TITLE
How to flash MHI-AC-Ctrl ?

### ISSUE THREAD

**Issue by artbrayko** [absalom-muc/MHI-AC-Ctrl#30]
Where to read the instructions to flash the MHI-AC-Ctrl device?
Thanks you

**Comment by absalom-muc** [comment]
For general handling of a ESP8266 (e.g. compile, upload/flash, log generation etc.) please use the Internet search. There are hundreds of web pages explaining the first steps. Thank you.

**Comment by absalom-muc** [comment]
If you have further more MHI-AC-Ctrl specific questions, please feel free to ask

**Comment by elrosso2** [comment]
Any link to a how to? I can not find a good webpage after a week of trying and searching.
