### ISSUE TITLE
Set define TEMP_MEASURE_PERIOD to 0 in default 

### ISSUE THREAD

**Issue by manoloxxl** [absalom-muc/MHI-AC-Ctrl#32]
Hi,

for newbies it would be easier if the default setting for the **optional** temp sensor would be set to disabled / 0

#define TEMP_MEASURE_PERIOD 30                      // period in seconds for temperature measurement with the external DS18x20 temperature sensor

Best Regards
Manuel

**Comment by absalom-muc** [comment]
Hi Manuel,

Thanks for your suggestion, I agree, disabling the optional temp sensor is a better starting point. I'll adapt it for the next version

**Comment by absalom-muc** [comment]
adapted in support.h und SW-Configuration.md
