### ISSUE TITLE
How to configure / update OTA?

### ISSUE THREAD

**Issue by manoloxxl** [absalom-muc/MHI-AC-Ctrl#37]
Hi, 

I've seen there is a OTA option. But i didn't find any advice how to handle it. By using IP or host-name i cannot access the device.

Is there a way to change the MQTT server adress or run an update without unmount the AC / remove the device from the AC?

Any hint?

Best Regards

Manuel

**Comment by thomas41587** [comment]
Hello Manuel,
never tried (or even thought) about OTA update. But the appropriate option is available in the editor: 
![grafik](https://user-images.githubusercontent.com/15812394/88802232-116a1880-d1ab-11ea-9646-9cc3393dd829.png)

**Comment by absalom-muc** [comment]
In the web you find many examples how to use OTA. And maybe this [hint](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Troubleshooting.md#fire-cant-see-the-device-in-in-arduino-ide-tools---port-for-ota) in the Troubleshooting Guide could help.

**Comment by manoloxxl** [comment]
My Arduino IDE is not showing any network-device.

As this is an issue on my system, i close this one. Thanks!
