### ISSUE TITLE
Link to "Operating data" needs to be updated

### ISSUE THREAD

**Issue by thomas41587** [absalom-muc/MHI-AC-Ctrl#38]
Hello,
As I am very interested in all these values I wanted to know the meaning of each of them. But the link within the SW-Configuration.md file seems to be outdated.
The new link (found via google search) is: https://www.hrponline.co.uk/media/pdf/5f/54/33/HRP_NEW_ServiceSupportHandbook.pdf
I know this is really something tiny but I guess it is worth updating the document :-)

**Comment by absalom-muc** [comment]
thank you, @FunkOdyssey2001 already made a [pull request](https://github.com/absalom-muc/MHI-AC-Ctrl/pull/36) related to this. I just changed it.
