### ISSUE TITLE
Wiring btw AC and MHI-AC-Ctrl

### ISSUE THREAD

**Issue by drdoener** [absalom-muc/MHI-AC-Ctrl#39]
Hi absalom,

thanks a lot for your great work. I´m about to solder the board and I´ve a question and input concerning the layout / wiring.
On the orange placards (/images/SRK-PCB.jpg and /images/SRK-PCB-RC.jpg) the order is GND,MISO,MOSI,SCL,+12V, beginning from 1.
This would mean 1 equals to GND.
On the pic below (AC_to_MHI-AC-Ctrl.png), PIN 1 equals to +12 V.
Please, could you explain the relationship between the pins on the boards and the information on the orange placards?

Thanks a lot,
Best,
drdoner

**Comment by absalom-muc** [comment]
Thank you @drdoener - you found a bug in AC_to_MHI-AC-Ctrl.png. There is the numbering of the AC connector wrong, it should be
![AC_to_MHI-AC-Ctrl2](https://user-images.githubusercontent.com/23119513/89463874-d0a46d80-d76f-11ea-88d4-f875fcd9adc2.png)
But the photos (incl. the orange placards in [SRK-PCB.jpg](../tree/master/images/SRK-PCB.jpg) and [SRK-PCB-RC.jpg](../tree/master/images/SRK-PCB-RC.jpg)) and the PCB show still the correct signal names.
I will update AC_to_MHI-AC-Ctrl.png accordingly.

**Comment by absalom-muc** [comment]
corrected [here](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/images/AC_to_MHI-AC-Ctrl.png)

**Comment by drdoener** [comment]
Hi,
fine, looks better now.
As soon as I will have installed the board, you receive feedback for my SRK 35 ZSX-W.

Greetz
