### ISSUE TITLE
AC is set to "Off" after iobroker restarts / wifi down

### ISSUE THREAD

**Issue by manoloxxl** [absalom-muc/MHI-AC-Ctrl#41]
Hi,

I'm running into an issue where the AC is powered off when the wifi network was down or i do a restart of iobroker.

How to reproduce:

> Connect the module with wifi
> Power AC an by IR Control
> Power Off WiFi
> Power On Wifi

OR

> Restart running iobroker instance during AC is powered on

After the module reconnects, the AC is set to "Off" and stops working.

Does anybody else noticed this behavior? I'm using the mqtt adapter (https://github.com/ioBroker/ioBroker.mqtt)

Best Regards
Manuel

**Comment by absalom-muc** [comment]
I believe this behaviour comes from ioBroker or your MQTT adapter. You could use [MQTT Explorer](http://mqtt-explorer.com/) - a great all-round MQTT client that provides a structured topic overview - for your investigation.

**Comment by manoloxxl** [comment]
Found the issue. The MQTT adapter sends all states on connect / subscribe. 

So when the AC is stopped by **not** the same device as it was startet, the "set" command contains the last submitted value that is different to the recent state.

I disabled the MQTT Adapter "send on start / subcribe" settings and now the AC is working as expected.
