### ISSUE TITLE
AC turns itself off after wifi goes down

### ISSUE THREAD

**Issue by fluffymadness** [absalom-muc/MHI-AC-Ctrl#43]
Hi, I'm using your interface with mqtt via homeassistant and right now I have the following problem:
I have a scheduled wifi that turns off during the night, and after the wifi goes down, the ac suddenly switches itself off too.
I could reproduce this behavior with the following steps:

- I turned on the AC via homeassistant
- (The AC remote ofc thinks the AC is off,because the status doesn't sync to the remote) So I pressed the power on button on the remote so I could change the temperature with the remote
- Then I went to my wifi router and pulled the plug

After about 1-2 minutes the AC is powering itself off.
Do you maybe have an idea what could cause this odd behavior and how to stop it?

**Comment by absalom-muc** [comment]
Few days ago we had a [similar issue](https://github.com/absalom-muc/MHI-AC-Ctrl/issues/41#issue-675678088). Maybe it helps.

**Comment by artbrayko** [comment]
Please write how you set up the work with the Home Assistant. I added to configuration.yaml this, but nothing works, but I see topics in  in Mqtt Explorer 

climate:
  - platform: mqtt
    name: Mitsubishi Heavy
    initial: 22
    min_temp: 18
    max_temp: 30
    modes:
      - "auto"
      - "dry"
      - "cool"
      - "fan_only"
      - "heat"
      - "off"
    swing_modes:
      - "1"
      - "2"
      - "3"
      - "4"
      - "Swing"
    fan_modes:
      - "1"
      - "2"
      - "3"
      - "4"
    mode_command_topic: "MHI-AC-Ctrl/set/Mode"
    mode_state_topic: "MHI-AC-Ctrl/Mode"
    temperature_command_topic: "MHI-AC-Ctrl/set/Tsetpoint"
    temperature_state_topic: "MHI-AC-Ctrl/Tsetpoint"
    fan_mode_command_topic: "MHI-AC-Ctrl/set/Fan"
    fan_mode_state_topic: "MHI-AC-Ctrl/Fan"
    swing_mode_command_topic: "MHI-AC-Ctrl/set/Vanes"
    swing_mode_state_topic: "MHI-AC-Ctrl/Vanes"
    current_temperature_topic: "MHI-AC-Ctrl/Troom"

**Comment by fluffymadness** [comment]
@artbrayko I used Daryn-L's changes from his github
for homeassistant two work. It is mostly an upper/lowercase problem with the mqtt topics.
https://github.com/Daryn-L/MHI-AC-Ctrl

**Comment by absalom-muc** [comment]
I assume the question is answered, so topic closed
