### ISSUE TITLE
Gerber files

### ISSUE THREAD

**Issue by heddock** [absalom-muc/MHI-AC-Ctrl#44]
Hi,

i'm looking forward to build you awesome project myself. I like to order some PCB but i need gerber files for that. Can you share those with me?

Thanks in advance.

Regards,

Frank

**Comment by absalom-muc** [comment]
Please find the Gerber files in this [issue](https://github.com/absalom-muc/MHI-AC-Ctrl/issues/2)

**Comment by heddock** [comment]
Thanks i received the PCB niet.
