### ISSUE TITLE
SRK-50-ZS-W in relation to Home Assistant (use of capitals to set mode)

### ISSUE THREAD

**Issue by henkjanvanderkolk** [absalom-muc/MHI-AC-Ctrl#58]
Many thanks for this great script. 

Plugged the unit in this afternoon and wanted to integrate it in Home Assistant with the The generic_thermostat climate platform. 

Setpoint, vane position and fan speed worked out of 'the box', but operating mode was returning 'invalid parameter on my MQTT listener. Changed the MQTT 'PAYLOAD_MODE' in MHI-AC-Ctrl.h:

- Auto -> auto
- Stop -> stop
- Dry -> dry
- Cool -> cool
- Fan -> fan_only
- Heat -> heat 

That did the trick on my SRK-50-ZSW. No fix needed - I suppose, just my experience with this particular type and integration.

**Comment by absalom-muc** [comment]
Thanks for the info @henkjanvanderkolk 
Only for completeness: We had similar topics already [here](https://github.com/absalom-muc/MHI-AC-Ctrl/issues/14) and [here](https://github.com/absalom-muc/MHI-AC-Ctrl/issues/29)

**Comment by henkjanvanderkolk** [comment]
My bad. Thank you.
