### ISSUE TITLE
ZSX signature ?

### ISSUE THREAD

**Issue by metarutaiga** [absalom-muc/MHI-AC-Ctrl#6]
My ZSX signature first byte is 0x6D, not 0x6C.

so I suggest the code
if ((rx_SPIframe[SB0] == 0x6c)
could be
if (((rx_SPIframe[SB0] & 0xfe) == 0x6c)

Thanks.

**Comment by absalom-muc** [comment]
Have you already tested that all commands are working in the same way as for the ZS series?
What is the exact name of the AC? Is it SRK xx ZSX-S for the indoor unit and SRC xx ZSX-S for the outdoor unit?

**Comment by metarutaiga** [comment]
Yes, it's ZSX series. The all command are almost working.
But some function like auto-fan and 6 level vanes and wide-vanes need to check who to set.

**Comment by absalom-muc** [comment]
Implemented in v1.3

**Comment by oliv3r** [comment]
@absalom-muc I wonder if we have any sense if this difference in siganture comes from the fact whether it uses 22 or 33 byte frames? I don't think we've seen a lot of signature bytes from users to make a sensible statement here?

**Comment by absalom-muc** [comment]
yes, this is correct.
