### ISSUE TITLE
Example: Node-Red integration with Google Assistant

### ISSUE THREAD

**Issue by pdufrenne** [absalom-muc/MHI-AC-Ctrl#60]
I want to share my Node-Red integration for this Heath-pump module.

It provides a dashboard for controlling the most important airconditioning functions.
But the best part it, provides integration with Google Assistant.
For Google-Assistent only a small sub-set of functions are available
With your voice you can set the set-point temperature, heat, cool or heat-cool function, request the actual room temperature and set the airco “off”.

Google Assistant integration is build with the new Smart-Nora service, which works fast and accurate.

You have to register an account at: https://smart-nora.eu/

You can use the code as an example for building your own dashboard and integration.

Succes!

Peter D.

[Heath-pump.json.txt](https://github.com/absalom-muc/MHI-AC-Ctrl/files/6421948/Heath-pump.json.txt)

![scaled Node-Red_Airco-Dashboard](https://user-images.githubusercontent.com/71838032/117023054-0a9fa180-acf9-11eb-8523-c98e5a3e6595.png)
![scaled Google-Home_2](https://user-images.githubusercontent.com/71838032/117023057-0bd0ce80-acf9-11eb-8191-2b06508ba812.png)
![scaled Google-Home_1](https://user-images.githubusercontent.com/71838032/117023065-0c696500-acf9-11eb-8230-2ff69c11db6c.png)

**Comment by absalom-muc** [comment]
Thanks for sharing @pdufrenne !
I added a link to this issue in [SW-Configuration](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#integration-examples)

**Comment by absalom-muc** [comment]
Since your integration is referenced in the documentation I close this issue. Thanks for sharing it.
