### ISSUE TITLE
External temperature sensor 

### ISSUE THREAD

**Issue by definable** [absalom-muc/MHI-AC-Ctrl#61]
I noticed the option for a temperature sensor. Can this sensor be used for the thermostat instead of the built-in sensor ? 
I like to have my temperature sensor in a slightly other location as the indoor unit. 

I know the MHI wired remote does have a sensor which can be used instead of (or in combination with, I do not know) the built in sensor, so it must be possible in addition to only sending the setpoint.

**Comment by absalom-muc** [comment]
I'm not aware this option. Do you have a link where it is described and  which wired remote supports it?

**Comment by waynethomas69** [comment]
I would love this feature too!!! The RC-E5 states that it has a "built-in temperature sensor"; I had assumed this would provide remote temperature values to the heat pumps it was controlling, but maybe not. I do have a spare RC-E5 lying around that I have no intent to ever install...

**Comment by waynethomas69** [comment]
There is a setting on the RC-E5, "09 Sensor Set" which has the following options (exact wording from the installation manual):
Sensor Off - Remote Thermistor is not working.
Sensor On - Remote Thermistor is working.
Sensor +3.0°C - Remote Thermistor is working, and to be set for producing +3.0°C increase in temperature.
etc. etc. etc.
This might suggest that the "built-in temperature sensor" provides data to the unit it is controlling.

With regards to installing multiple remote controllers, the instructions state:
"Note: The setting "Remote controller thermistor enabled" is only selectable with the master remote
controller in the position where you want to check room temperature"

Finally, from www.mitsuheavy.vn site (not my poor English...):
4. ROOM TEMPERATURE IS ADJUSTED BY THE SENSOR ON THE CONTROL
The temperature sensor is located on the upper inner part of the controller. This arrangement improves the sensitivity of the sensor. Allow to adjust the air temperature is better.

None of this states for certain that it provides a remote room temperature reading to the unit it is controlling, but I had made this assumption.

**Comment by absalom-muc** [comment]
> There is a setting on the RC-E5, "09 Sensor Set" which has the following options (exact wording from the installation manual):

@waynethomas69 Could you provide a link to your installation manual? I can't find sensor related statements e.g. [here](https://www.mhi-mth.co.jp/en/products/pdf/pjz012a087b_english.pdf)

**Comment by waynethomas69** [comment]
Found a copy of it here: http://www.bvtpartners.ee/page/wp-content/uploads/mitsubishi/manuals/RC-E5_Service_manual.pdf

**Comment by absalom-muc** [comment]
Thank you, found it. I'll come back to you...

**Comment by absalom-muc** [comment]
I found out how it works and plan to issue a new release with the following options for the room temperature:

1.  use temperatur sensor from AC indoor unit (default)
2.  use temperature from DS18x20 sensor
3.  use temperature provided via MQTT

Maybe with the possibility for an offset for option 2 and 3.
If you have further ideas please feel free to make a proposal.

**Comment by waynethomas69** [comment]
Great news, well done!
One thought about option 3 - when using an external sensor over MQTT (this is my intent), perhaps the controller should have a timeout/watchdog that will default back to the internal sensor if a temperature update is not received within a certain amount of time (i.e. 30 minutes). This way the AC will still remain functional if there is an issue with MQTT or the external sensor fails.
If MHI-AC-Ctrl doesn't include this functionality it will still be easy enough to implement separately (i.e. node-red), but it would be worth recommending users do this if using an external sensor.
I'm very excited for this feature, as the internal sensor tends to be inaccurate when the AC first turns on, and when it turns off.

**Comment by damienmorrissey** [comment]
This is a very good feature and will probably make the system more
effective at controlling temperature. A seperate temperature sensor closer
to where people are located in a room will make a big difference.

**Comment by absalom-muc** [comment]
Please find the updated version. Configuration is explained in [SW-Configuration](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#room-temperature)

**Comment by waynethomas69** [comment]
Excellent, great effort working this out from what little information was provided in the vague manual references. I will hopefully test this weekend.
Some questions regarding the ROOM_TEMP_MQTT_TIMEOUT option:
- just confirming this is seconds, not minutes?
- if the timeout occurs, and the system falls back to IU Temperature, will it return to using the MQTT room temperature if the MQTT messages resume?
Thanks again!

**Comment by absalom-muc** [comment]
>     * just confirming this is seconds, not minutes?
yes, ROOM_TEMP_MQTT_TIMEOUT  is in seconds
>     * if the timeout occurs, and the system falls back to IU Temperature, will it return to using the MQTT room temperature if the MQTT messages resume?
yes

**Comment by DYLaKo** [comment]
I am looking into this feature to use it with the temperature reported by the room thermostat from the CV, but I am not sure to which topic I need to push the temperature. If I read the files correctly, it seems that I need to push it to the "Troom" topic, but with my current running firmware (v2.03), "Troom" is already used by the AC itself.

So does that mean "Troom" is with this new setup only used for external input, or also for input from the AC itself?

**Comment by absalom-muc** [comment]
In general, Troom is used by the internal control loop of the AC to control the level of cooling/heating.
Troom can be fed by different inputs. Per default, or when using 
`#define ROOM_TEMP_IU`
Troom is fed by the room temperature sensor of the AC.

When using 
`#define ROOM_TEMP_DS18X20`
Troom is fed by the external DS18x20, the AC internal sensor is no longer used.

When using
`#define ROOM_TEMP_MQTT`
it is expected that the user feeds Troom in an interval < ROOM_TEMP_MQTT_TIMEOUT by pushing the room temperature via MQTT. Please consider that the MQTT path for the status (read from user's perspective) is different from the MQTT path for setting (write from user's perspective) , please check clause [MQTT status](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md#mqtt-status).

Does it clarifying the approach?

**Comment by DYLaKo** [comment]
I think I understand now. Both the AC and the external MQTT input use Troom, but when I set it from MQTT, I need to push it to the /set/Troom topic, right?

If I use this approach, is it still possible to read the real temperature value of the AC?

**Comment by absalom-muc** [comment]
> 
> 
> I think I understand now. Both the AC and the external MQTT input use Troom, but when I set it from MQTT, I need to push it to the /set/Troom topic, right?

yes
> If I use this approach, is it still possible to read the real temperature value of the AC?

usually Troom and RETURN-AIR are equal. Maybe the room temperature from AC sensor is still provided via RETURN-AIR, but I haven't tested it.

**Comment by DYLaKo** [comment]
Thank you for the clarification, I will test this out next week.

**Comment by absalom-muc** [comment]
I tested it, seems that Troom and RETURN-AIR are always equal independent from the source of the room temperature. So no idea how to get the temperature value from AC when using an external sensor.

**Comment by th3sniper86** [comment]
![image](https://user-images.githubusercontent.com/57175617/144451842-03a754a9-8a43-4113-8df1-9f5002f23907.png)
Updating Troom using mqtt is not working for me. timout set to 14400 sec.

**Comment by absalom-muc** [comment]
Is there a general problem with writing? Was writing of Tsetpoint not considered?

**Comment by th3sniper86** [comment]
When I test it now, it is instant. Maybe my mqtt system is/was a bit slow..

**Comment by absalom-muc** [comment]
close this issue, since it is solved. If not, feel free to reopen it.
(in general I would appreciate when the person opening an issue also close it)
