### ISSUE TITLE
Carbon Dioxide MH-Z19B integration

### ISSUE THREAD

**Issue by th3sniper86** [absalom-muc/MHI-AC-Ctrl#72]
Maybe a nice enhancement: Replace the ds18b20 with a MH-Z19B to monitor temperature and co2 to also give an idea about the air quality.

https://www.winsen-sensor.com/sensors/co2-sensor/mh-z19b.html

**Comment by absalom-muc** [comment]
There are a lot of sensors which could be used, but with MHI-AC-Ctrl I would like to focus on the core functionality and therefore don't intend to support further sensors.
