### ISSUE TITLE
set/Troom precision

### ISSUE THREAD

**Issue by kARTechnology** [absalom-muc/MHI-AC-Ctrl#74]
How to get .5 precision for setting the target room temperature. the ac does support this as in eco mode by remote it operates 1.5 deg.. higher than set temperature.

**Comment by absalom-muc** [comment]
By intention it is not supported. That would only counterfei an accuracy for the temperature measurement and control that the AC cannot achieve.

**Comment by kARTechnology** [comment]
> By intention it is not supported. That would only counterfei an accuracy for the temperature measurement and control that the AC cannot achieve.

the ac does support upto 0.5 degree precision. i think then the only way to get that precision is to get the eco mode working
![image](https://user-images.githubusercontent.com/24961429/145327608-278c3fcb-2247-4de3-992a-dc507218ed0a.png)

**Comment by absalom-muc** [comment]
we have a misunderstanding, the AC supports the higher resolution. MHI-AC-Ctrl doesn't support it because see above
