### ISSUE TITLE
room temperature lower than set Temperature by 2 degree

### ISSUE THREAD

**Issue by kARTechnology** [absalom-muc/MHI-AC-Ctrl#76]
I have been using the set/Troom from external sensor. sensor reports 24, ac reports the same. but the set temperature is 26.
any further tests to be done? target temp reporting is correct as ac remote corresponds to the one displayed by mqtt. but is the room temperature reading flawed? even if the external sensor is not calibrated, set temp must be equal to room temp.
![image](https://user-images.githubusercontent.com/24961429/145756005-b78e98ef-25b1-4211-882b-e8296370a487.png)

**Comment by absalom-muc** [comment]
The diagram is a little bit confusing for me.
What is the time slot in your scope? 1am-4:30pm?
Which mode do you use? COOL?
Have you made the identical test with the internal room temperatur sensor?

**Comment by damienmorrissey** [comment]
If it helps this happens to me with the standard remote in cool mode. Set
to 23 and the room will be 21 as per other measurements. This is with an
old 2.5kW split system.

**Comment by kARTechnology** [comment]
> 

this is with new inverter series.
