### ISSUE TITLE
Idea to improve precision

### ISSUE THREAD

**Issue by ph-pk** [absalom-muc/MHI-AC-Ctrl#81]
The MHI units have a precision of 1.0C for setpoint. Additionally, troom is rounded down to .0 / 0.25 / .5 / .75 causing an additional loss of precision for unit control logic when e.g. an external sensor with MQTT is used.

To improve this behavior I prototyped the following:
- properly round set/Tsetpoint to nearest integer
- store difference as offset
- correct set/Troom with offset
- properly round corrected troom to nearest 0.25

This emulates a precision of 0.25C, max difference 0.125C.

Would this be something to include?

**Comment by kARTechnology** [comment]
i think 0.5 deg precision is possible as in eco mode it is using set temp=set temp+1.5deg 
anyone with wired remote can tell if it is possible to set in 0.5 deg steps

**Comment by kARTechnology** [comment]
https://github.com/absalom-muc/MHI-AC-Ctrl/issues/74

**Comment by absalom-muc** [comment]
> The MHI units have a precision of 1.0C for setpoint. Additionally, troom is rounded down to .0 / 0.25 / .5 / .75 causing an additional loss of precision for unit control logic when e.g. an external sensor with MQTT is used.
> 
> To improve this behavior I prototyped the following:
> 
>     * properly round set/Tsetpoint to nearest integer
> 
>     * store difference as offset
> 
>     * correct set/Troom with offset
> 
>     * properly round corrected troom to nearest 0.25
> 
> 
> This emulates a precision of 0.25C, max difference 0.125C.
> 
> Would this be something to include?

Thanks for your suggestion @ph-pk.

Not sure that I understand it completely. Some comments:

- The resolution (not the precision) for the setpoint was 1°C so far, but it changed with v2.5R21 to 0.5°C (btw: I missed to mention this in [Version.md](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Version.md))
- Troom resolution is 0.25°C. Also when you send the room temperature via MQTT then MHI-AC-Ctrl writes this value (with the resolution of 0.25°C) to the AC unit. But only changes>=0.5°C will be published as discussed in your issue #82. 
- The measurement of the room temperature has according to my experience usually an accuracy >1°C. But I don't see that as a problem since the human temperature sense is not stable. Using a higher resolution would only counterfei an accuracy for the temperature measurement and control that is not given.

That's why I'm rather reluctant when it comes to supposed ideas for increasing accuracy.

**Comment by pkoster** [comment]
(issue was created with wrong account)

> * The resolution (not the precision) for the setpoint was 1°C so far, but it changed with v2.5R21 to 0.5°C (btw: I missed to mention this in [Version.md](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Version.md))

I performed an experiment to validate this. Logged values to Influxdb and visualized with Grafana.
The findings contradict with 0.5°C and confirm 1.0°C resolution:
- the unit switches down/off when troom/op_returnair reaches op_tsetpoint. The unit switches up/on when troom/op_returnair falls below op_tsetpoint.
- op_tsetpoint has a resolution of 1.0°C (setpoint/set_setpoint + 2.0 rounded up)
- the resulting temperature subsequently centers around op_tsetpoint

Example: set_setpoint=18.5°C leads to setpoint=18.5°C with op_setpoint=21.0°C and also a resulting temperature around 21.0°C.

Conclusion: it is possible to specify setpoint with 0.5°C resolution but the effective resolution is 1.0°C.

![original_2-3-2022_annotated](https://user-images.githubusercontent.com/1622812/156447113-ed91b99d-e78a-442c-8d39-72b5156afe73.png)

> * Troom resolution is 0.25°C. Also when you send the room temperature via MQTT then MHI-AC-Ctrl writes this value (with the resolution of 0.25°C) to the AC unit. But only changes>=0.5°C will be published as discussed in your issue [MQTT Troom update on smallest change #82](https://github.com/absalom-muc/MHI-AC-Ctrl/issues/82).

Will get back to this separately.

> * The measurement of the room temperature has according to my experience usually an accuracy >1°C. But I don't see that as a problem since the human temperature sense is not stable. Using a higher resolution would only counterfei an accuracy for the temperature measurement and control that is not given.

Humans (and some thermometers) are indeed bad at measuring absolute temperature, but pretty good at sensing relative temperature differences. Particularly for people, 0.5°C difference can make a real-world difference between comfortable and non-comfortable.

Therefore, I'd argue to at least try to support 0.5°C (and more where possible).

Below is a quick & dirty example to achieve a 20.5°C temperature.
![modified_28-2-2022b_annotated](https://user-images.githubusercontent.com/1622812/156450615-ebd84797-6086-4a38-ae49-ca756093db17.png)

**Comment by absalom-muc** [comment]
Thanks for the explanation and the diagrams, I see the reduced variation of set_troom.

Some topics are still unclear for me:
- I assume troom is hiden by op_returnair because they are equal, please confirm.
- Why is set_setpoint (red) not equal to setpoint (dark blue) in the second diagram? In the first diagram they are equal.

To be honest I can still not comprehend that the 0.5°C should make a big difference, but I accept that other persons might feel different.

Have you implemented your changes in MHI-AC-Core-ctrl.cpp only or are other files affected, too?

**Comment by kARTechnology** [comment]
Hi @ph-p

> The MHI units have a precision of 1.0C for setpoint. Additionally, troom is rounded down to .0 / 0.25 / .5 / .75 causing an additional loss of precision for unit control logic when e.g. an external sensor with MQTT is used.
> 
> To improve this behavior I prototyped the following:
> 
>     * properly round set/Tsetpoint to nearest integer
> 
>     * store difference as offset
> 
>     * correct set/Troom with offset
> 
>     * properly round corrected troom to nearest 0.25
> 
> 
> This emulates a precision of 0.25C, max difference 0.125C.
> 
> Would this be something to include?

Hi, can you share the changes made in code to get more tighter control of the set temperature?

Also is actual set temperature = tsetpoint-2 degree c?

**Comment by rwijnhov** [comment]
@pkoster could you post your changes?

**Comment by pkoster** [comment]
@absalom-muc : the diagrams were made with slight differences in code that did / did not correct MQTT values like setpoint (dark blue) for the offset.

@kARTechnology : the code below does not incorporate the -2 offset 

@rwijnhov : 
Below is a unified diff, which has been subsequently manually stripped of configuration, non-working extensions, etc. (untested).

`diff -U 5 ../MHI-AC-Ctrl/src/MHI-AC-Ctrl-core.cpp MHI-AC-Ctrl/MHI-AC-Ctrl-core.cpp
--- ../MHI-AC-Ctrl/src/MHI-AC-Ctrl-core.cpp	2022-01-09 15:01:48.503850946 +0100
+++ MHI-AC-Ctrl/MHI-AC-Ctrl-core.cpp	2022-03-05 00:28:00.539499083 +0100
@@ -139,17 +139,41 @@
 
 void MHI_AC_Ctrl_Core::request_ErrOpData() {
   request_erropData = true;
 }
 
+float MHI_AC_Ctrl_Core::get_troom_offset() {
+  return Troom_offset;
+}
+
+void MHI_AC_Ctrl_Core::set_troom_offset(float offset) {
+  Troom_offset = offset;
+}
+
+int MHI_AC_Ctrl_Core::get_opdata_tsetpoint() {
+  return opdata_tsetpoint;
+}
+
+int MHI_AC_Ctrl_Core::get_status_tsetpoint() {
+  return status_tsetpoint;
+}
+
 #ifndef ROOM_TEMP_IU
 void MHI_AC_Ctrl_Core::set_troom(byte troom) {
   Serial.printf("MHI_AC_Ctrl_Core::set_troom %i\n", troom);
   new_Troom = troom;
 }
@@ -294,17 +318,18 @@
       }
       status_vanes_old = vanestmp;
     }
 
     int8_t troom_diff = MOSI_frame[DB3] - status_troom_old; // avoid using other functions inside the brackets of abs, see https://www.arduino.cc/reference/en/language/functions/math/abs/
-    if (abs(troom_diff) > 1) { // Room temperature delta > 0.25°C
+    if (abs(troom_diff) > 0) { // Room temperature delta > 0.0°C
       status_troom_old = MOSI_frame[DB3];
       m_cbiStatus->cbiStatusFunction(status_troom, status_troom_old);
     }
 
     if (MOSI_frame[DB2] != status_tsetpoint_old) { // Temperature setpoint
@@ -545,7 +571,19 @@
         break;
       default:    // unknown operating data
         m_cbiStatus->cbiStatusFunction(opdata_unknwon, MOSI_frame[DB10] << 8 | MOSI_frame[DB9]);
     }
   }
+  
+  if (Troom_offset != Troom_offset_old) {
+	  Troom_offset_old = Troom_offset;
+	  m_cbiStatus->cbiStatusFunction(troom_offset, (int)(Troom_offset*1000.0));
+  }
+  
   return call_counter;
 }
diff -U 5 ../MHI-AC-Ctrl/src/MHI-AC-Ctrl-core.h MHI-AC-Ctrl/MHI-AC-Ctrl-core.h
--- ../MHI-AC-Ctrl/src/MHI-AC-Ctrl-core.h	2022-01-09 15:01:48.503850946 +0100
+++ MHI-AC-Ctrl/MHI-AC-Ctrl-core.h	2022-03-02 23:19:10.322983463 +0100
@@ -61,10 +61,11 @@
   type_status = 0x40, type_opdata = 0x80, type_erropdata = 0xc0
 };
 
 enum ACStatus { // Status enum
   status_rssi = type_status, status_mqtt_lost, status_wifi_lost, status_connected, status_cmd, status_tds1820, status_fsck, status_fmosi, status_fmiso, status_power, status_mode, status_fan, status_vanes, status_troom, status_tsetpoint, status_errorcode,
+  troom_offset, 
   opdata_mode = type_opdata, opdata_tsetpoint, opdata_return_air, opdata_outdoor, opdata_tho_r1, opdata_iu_fanspeed, opdata_thi_r1, opdata_thi_r2, opdata_thi_r3,
   opdata_ou_fanspeed, opdata_total_iu_run, opdata_total_comp_run, opdata_comp, opdata_ct, opdata_td,
   opdata_tdsh, opdata_protection_no, opdata_defrost, opdata_ou_eev1, opdata_unknwon,
   erropdata_mode = type_erropdata, erropdata_tsetpoint, erropdata_return_air, erropdata_thi_r1, erropdata_thi_r2, erropdata_thi_r3,
   erropdata_iu_fanspeed, erropdata_total_iu_run, erropdata_outdoor, erropdata_tho_r1, erropdata_comp, erropdata_td, erropdata_ct, erropdata_ou_fanspeed,
@@ -128,10 +129,15 @@
     byte new_Vanes0 = 0;
     byte new_Vanes1 = 0;
     bool request_erropData = false;
     byte new_Troom = 0xff;
 
+    float Troom_offset = 0.0;
+  	 float Troom_offset_old = 999.0;
+    
     CallbackInterface_Status *m_cbiStatus;
 
   public:
     void MHIAcCtrlStatus(CallbackInterface_Status *cb) {
       m_cbiStatus = cb;
@@ -145,8 +151,14 @@
     void set_tsetpoint(uint tsetpoint);   // set the target temperature of the AC)
     void set_fan(uint fan);               // set the requested fan speed
     void set_vanes(uint vanes);           // set the vanes horizontal position (or swing)
     void request_ErrOpData();             // request that the AC provides the error data
     void set_troom(byte temperature);     // set the room temperature used by AC
+    float get_troom_offset();
+    void set_troom_offset(float offset);
+    int get_opdata_tsetpoint();
+    int get_status_tsetpoint();
 };
 
 #endif
diff -U 5 ../MHI-AC-Ctrl/src/MHI-AC-Ctrl.h MHI-AC-Ctrl/MHI-AC-Ctrl.h
--- ../MHI-AC-Ctrl/src/MHI-AC-Ctrl.h	2022-06-11 15:33:29.141703453 +0200
+++ MHI-AC-Ctrl/MHI-AC-Ctrl.h	2022-03-02 23:03:35.426635780 +0100
@@ -20,10 +20,13 @@
 #define TOPIC_VANES "Vanes"
 #define TOPIC_TROOM "Troom"
 #define TOPIC_TSETPOINT "Tsetpoint"
 #define TOPIC_ERRORCODE "Errorcode"
 
+#define TOPIC_TROOM_OFFSET "Troom_offset"
+
 #define TOPIC_RETURNAIR "RETURN-AIR"
 #define TOPIC_THI_R1 "THI-R1"
 #define TOPIC_THI_R2 "THI-R2"
 #define TOPIC_THI_R3 "THI-R3"
 #define TOPIC_IU_FANSPEED "IU-FANSPEED"
diff -U 5 ../MHI-AC-Ctrl/src/MHI-AC-Ctrl.ino MHI-AC-Ctrl/MHI-AC-Ctrl.ino
--- ../MHI-AC-Ctrl/src/MHI-AC-Ctrl.ino	2022-01-09 15:01:48.503850946 +0100
+++ MHI-AC-Ctrl/MHI-AC-Ctrl.ino	2022-03-05 00:08:34.568940697 +0100
@@ -73,12 +73,36 @@
       else
         publish_cmd_invalidparameter();
   }
   else if (strcmp_P(topic, PSTR(MQTT_SET_PREFIX TOPIC_TSETPOINT)) == 0) {
     float f=atof((char*)payload);
-    if((f >= 18) & (f <= 30))
+#ifdef ENHANCED_RESOLUTION	
+    float fenh = round(f);
+    if(fenh < 18.0) {
+      fenh = 18.0;
+    }
+    if(fenh > 30.0) {
+      fenh = 30.0;
+    }
+    float offset = fenh - f;
+    mhi_ac_ctrl_core.set_troom_offset(offset);
+    f = fenh;
+#endif
+    if((f >= 18) & (f <= 30)) {
       mhi_ac_ctrl_core.set_tsetpoint((byte)(2 * f));
+    }
     else
       publish_cmd_invalidparameter();
   }
   else if (strcmp_P(topic, PSTR(MQTT_SET_PREFIX TOPIC_FAN)) == 0) {
     if ((atoi((char*)payload) >= 1) & (atoi((char*)payload) <= 4)) {
@@ -103,14 +127,18 @@
     }
   }
 #ifdef ROOM_TEMP_MQTT
   else if (strcmp_P(topic, PSTR(MQTT_SET_PREFIX TOPIC_TROOM)) == 0) {
     float f=atof((char*)payload);
+#ifdef ENHANCED_RESOLUTION
+    float offset = mhi_ac_ctrl_core.get_troom_offset();
+    f = f + offset + 0.125;
+#endif
     if ((f > -10) & (f < 48)) {
       room_temp_MQTT_timeout_Millis = millis();  // reset timeout
       byte tmp = f*4+61;
-      mhi_ac_ctrl_core.set_troom(f*4+61);
+      mhi_ac_ctrl_core.set_troom(tmp);
       Serial.printf("ROOM_TEMP_MQTT: %f %i %i\n", f, (byte)(f*4+61), (byte)tmp);
       publish_cmd_ok();
     }
     else
       publish_cmd_invalidparameter();
@@ -136,10 +164,12 @@
 class StatusHandler : public CallbackInterface_Status {
   public:
     void cbiStatusFunction(ACStatus status, int value) {
       char strtmp[10];
       static int mode_tmp = 0xff;
+      float offset = mhi_ac_ctrl_core.get_troom_offset();
+
       //Serial.printf_P(PSTR("status=%i value=%i\n"), status, value);
       switch (status) {
         case status_fsck:
           itoa(value, strtmp, 10);
           output_P(status, PSTR(TOPIC_FSCK), strtmp);
@@ -207,13 +237,21 @@
               itoa(value, strtmp, 10);
               output_P(status, PSTR(TOPIC_VANES), strtmp);
           }
           break;
         case status_troom:
-          dtostrf((value - 61) / 4.0, 0, 2, strtmp);
+          dtostrf((value - 61) / 4.0 - offset, 0, 2, strtmp);
           output_P(status, PSTR(TOPIC_TROOM), strtmp);
           break;
+        case troom_offset:
+          dtostrf(value/1000.0, 0, 2, strtmp);
+          output_P(status, PSTR(TOPIC_TROOM_OFFSET), strtmp);
+          break;	   
         case status_tsetpoint:
         case opdata_tsetpoint:
         case erropdata_tsetpoint:
           dtostrf((value & 0x7f)/ 2.0, 0, 1, strtmp);
           output_P(status, PSTR(TOPIC_TSETPOINT), strtmp);
@@ -223,11 +261,11 @@
           itoa(value, strtmp, 10);
           output_P(status, PSTR(TOPIC_ERRORCODE), strtmp);
           break;
         case opdata_return_air:
         case erropdata_return_air:
-          dtostrf((value - 61) / 4.0, 0, 2, strtmp);
+          dtostrf((value - 61) / 4.0 - offset, 0, 2, strtmp);
           output_P(status, PSTR(TOPIC_RETURNAIR), strtmp);
           break;
         case opdata_thi_r1:
         case erropdata_thi_r1:
           itoa(0.327f * value - 11.4f, strtmp, 10); // only rough approximation
diff -U 5 ../MHI-AC-Ctrl/src/support.h MHI-AC-Ctrl/support.h
--- ../MHI-AC-Ctrl/src/support.h	2022-01-09 15:01:48.503850946 +0100
+++ MHI-AC-Ctrl/support.h	2022-03-02 23:21:23.385894871 +0100
@@ -30,22 +30,25 @@
                                                     // enter 0 if you don't use the DS18x20 
 #define ONE_WIRE_BUS 4                              // D2, PIN for connecting temperature sensor DS18x20 DQ pin
 
 // Per default AC internal sensor is used for the room temperature. You can select using the DS18x20 sensor or providing Troom via MQTT.
 //#define ROOM_TEMP_DS18X20                         // use room temperature from DS18x20
-//#define ROOM_TEMP_MQTT                            // use room temperature from received MQTT topic
-#define ROOM_TEMP_MQTT_TIMEOUT  20                  // only considered if ROOM_TEMP_MQTT is defined
+#define ROOM_TEMP_MQTT                            // use room temperature from received MQTT topic
+#define ROOM_TEMP_MQTT_TIMEOUT  300                  // only considered if ROOM_TEMP_MQTT is defined
                                                     // time in seconds, after this time w/o receiving a valid room temperature
                                                     // via MQTT fallback to IU temperature sensor value
 
 //#define POWERON_WHEN_CHANGING_MODE true           // uncomment it to switch on the AC when the mode (heat, cool, dry etc.) is changed
                                                     // used e.g. for home assistant support
 
+#define ENHANCED_RESOLUTION true
+
 // *** The configuration ends here ***
                                                     
 #include <ESP8266WiFi.h>        // https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi
 #include <PubSubClient.h>       // https://github.com/knolleary/pubsubclient
 #include <ArduinoOTA.h>         // https://github.com/esp8266/Arduino/tree/master/libraries/ArduinoOTA
`

**Comment by absalom-muc** [comment]
Not sure if you plan a pull-request, else please consider to close the issue

**Comment by rwijnhov** [comment]
Could we please incorporate the .5 temp settings in the base code? I use external sensors. And 22 is too cold and 23 too warm :) 22.5 is the temp I need.

**Comment by absalom-muc** [comment]
> Could we please incorporate the .5 temp settings in the base code? I use external sensors. And 22 is too cold and 23 too warm :) 22.5 is the temp I need.

Tsetpoint resolution of 0.5°C is already implemented since December 2021, please see https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md.

For the precision improve, someone has to initiate a pull-request, I don't plan it currently.

**Comment by rwijnhov** [comment]
Yes I know but it doesn't work. If i set it to 22.5 it will still heat to 23 degrees same behaviour if inset it to 23.

**Comment by glsf91** [comment]
I have made some changes so the setpoint of .5 degrees are working, based on the diff pkoster has supplied. But I made some changes to make it also work with a connected external DS18B20. Also when the wemos is reset or the remote control is used.
Basically the Troom send to the airco will be increased with an offset (0.5 degrees) when a setpoint x.5 degrees is used. 
I have to test this more, but I will make a pull request when finished.

**Comment by glsf91** [comment]
Made a pull request for changing Tsetpoint resolution as discussed above. I used the diff supplied by @pkoster (thanks !) but changed a few things to make it work also after a reset of the wemos and when using the remote control.
Tested a lot with external sensor but also with set/Troom MQTT.

**Comment by absalom-muc** [comment]
implemented in v2.6
