### ISSUE TITLE
No CNS connector soldered

### ISSUE THREAD

**Issue by kARTechnology** [absalom-muc/MHI-AC-Ctrl#85]
I have 2 MHI ac,s 
one is variable inverter technology  (SRK-18YXS2-W6, 1.65 ton, 5.7* ISEER)(Has inbuilt humidity sensor too)
and another is non inverter fixed speed unit (SRK-25CWX-S6 - 1.95 ton, 4.2* ISEER) , **NO OUTDOOR UNIT COMMNUNICATION**

 I was able to successfully implement mhi-ac-ctrl in the inverter model and working fine since many months,
Today i opened the non-inverter model to add the CNS cable and check if mhi-ac-ctrl will work.. but to my surprise i found the connector is not soldered..

My question is how to know
![INVERTER IDU](https://user-images.githubusercontent.com/24961429/164771524-f42b868e-8223-453b-a778-c49f1ef84715.jpg)

![NON INVERTER IDU](https://user-images.githubusercontent.com/24961429/164771803-12e729d8-f5fb-4b5a-83b4-4e310b995db7.jpg)

 if the Indoor unit supports CNS monitoring? (Basic on/off/mode/temperature/speed/vales/swing)
before i solder on a CNS connector i want to know how i can test if the unit is outputting any data for communication?

**Comment by absalom-muc** [comment]
It is also suprising for me. I don't know if the second unit provides the required SPI signals. You could measure the voltage on the pins, the levels described [here](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Troubleshooting.md#fire-pins-not-properly-connected). But this is complicated and dangerous becuase there are no solder pads on the top of the PCB.

**Comment by kARTechnology** [comment]
> It is also suprising for me. I don't know if the second unit provides the required SPI signals. You could measure the voltage on the pins, the levels described [here](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Troubleshooting.md#fire-pins-not-properly-connected). But this is complicated and dangerous becuase there are no solder pads on the top of the PCB.

It does look to have the pads, but no socket soldered. this is a single sided pcb only right?
it would not have the sensor values other than indoor temp sensor, pipe sensor.
in such case what would mhi-ac-ctrl try to collect from the unit? outdoor unit values are not available.

**Comment by absalom-muc** [comment]
> It does look to have the pads, but no socket soldered. this is a single sided pcb only right? it would not have the sensor values other than indoor temp sensor, pipe sensor. in such case what would mhi-ac-ctrl try to collect from the unit? outdoor unit values are not available.

Solder pads seem to be on the bottom side only, so yes, it is a single sided pcb. I don't know which values are used from this indoor unit.

**Comment by kARTechnology** [comment]
It seems like only the models with ODU communication cable support CNS. I found the backside of **pcb not having required components** for cns to work. but 12v and gnd available. need to see if i can implement IR control with a buck converter+esp8266
![image](https://user-images.githubusercontent.com/24961429/167831883-9edc2403-c78a-49cc-84a2-05e3cb452f53.png)
