### ISSUE TITLE
Read values in code

### ISSUE THREAD

**Issue by kARTechnology** [absalom-muc/MHI-AC-Ctrl#87]
How to read the AC Power,Temperature,Fan,Swing status in arduino code itself? I was able to get mhi-ac-ctrl to send data to influ and also host a webserver to accept commands, but how do i read the values to display the current state...
`
 String("<html><body> <h1>MHI-AC-CONTROL "+String(status_power)+"-"+String(status_tsetpoint)+"</body></html>"));`
![image](https://user-images.githubusercontent.com/24961429/168651216-7c4f223f-5c6e-45d6-a007-ba31c7ff5587.png)

**Comment by absalom-muc** [comment]
I suggest you use CallbackInterface_Status (row 176 in MHI-AC-Ctrl.ino). All status information are delivered to this class and inside the switch comand you can select the information you are interested. You could replace the output_p call by your comand to display the status.

**Comment by kARTechnology** [comment]
> I suggest you use CallbackInterface_Status (row 176 in MHI-AC-Ctrl.ino). All status information are delivered to this class and inside the switch comand you can select the information you are interested. You could replace the output_p call by your comand to display the status.

Pls help me with example to read fanspeed/set temp/returnair..

**Comment by absalom-muc** [comment]
Not sure related to your yellow and red marking. But e.g. below the line with power=1 or power=0 you could make the output to your display,

**Comment by kARTechnology** [comment]
Thanks. Added web server and http updater, influxdb. and can use cron to send schedule by http commands(my mqtt broker is openwrt router)

![image](https://user-images.githubusercontent.com/24961429/169207301-d1f472b5-152d-41f6-bb81-d1fb51f2d740.png)
