### ISSUE TITLE
use 0.5 degrees as temp setting?

### ISSUE THREAD

**Issue by rwijnhov** [absalom-muc/MHI-AC-Ctrl#92]
Is it possible to set the temp on 0.5 degrees somehow? I would  like to use a temp setting of 22.5 degrees if that is possibe somehow?

**Comment by kARTechnology** [comment]
yes possible with latest firmware. but in my case if u turn off the ac and back on it loses the precision. dont know why.

**Comment by absalom-muc** [comment]
Tsetpoint supports a resolution of 0.5°C, just added this information to the documentation.

>back on it loses the precision. dont know why

I can't confirm this behaviour for my AC, the resolution of 0.5°C is still given after a power off/on cycle.

**Comment by rwijnhov** [comment]
What firmware update?

**Comment by rwijnhov** [comment]
I already use v2.5R21

**Comment by absalom-muc** [comment]
Please provide a log file.

**Comment by absalom-muc** [comment]
I believe the issue was addressed, therefore closed. If there are further questions, please feel free to re-open it.

**Comment by kARTechnology** [comment]
You can set 24,24.5,25 like that only in 0.5 degree precision.
