### ISSUE TITLE
Omit level shifter?

### ISSUE THREAD

**Issue by nmg196** [absalom-muc/MHI-AC-Ctrl#94]
Hi
Just wondering - as the ESP8266 is 5V tolerant on the data pins, can the level shifter be safely omitted or have people encountered problems?  I'm trying to avoid the need for a custom PCB as that makes it dramatically more complex for me.

Thanks!
Nick

**Comment by absalom-muc** [comment]
We had this discussion already [here](https://github.com/absalom-muc/MHI-AC-Ctrl/issues/65). My recommendation is still using the level shifter as long there is no official statement in the datasheet related to 5V tolerance.

**Comment by nmg196** [comment]
Thanks - there is an official statement about it which I have now posted about on the original issue you linked to. 

I will close this as a duplicate.
