### ISSUE TITLE
How do you add the device to Home Assistant?

### ISSUE THREAD

**Issue by nmg196** [absalom-muc/MHI-AC-Ctrl#96]
I'm finally getting somewhere and i'm up and running with the software side. 
However I've not used Home Assistant before so I'm not sure of the next step.

- I have installed an MQTT broker on my NAS.
- I have flashed my Wemos D1 with the compiled firmware.
- The device is succesfully communicating with Broker as I can see this in MQTT explorer:
- 
![image](https://user-images.githubusercontent.com/8134047/174608999-1321aa9b-90be-411e-ba54-2784253589c1.png)

...but how do I actually control the A/C?  It doesn't seem to be listed as an "entity" and I can't find any reference to it in HA, despite having connected HA to my MQTT Broker.

I found some YAML in another issue (https://github.com/absalom-muc/MHI-AC-Ctrl/files/6404612/IoTMQTTPanel-210330_095559.txt)
...but this doesn't seem to work in HA as it's missing the "type" property.

**Comment by nmg196** [comment]
Thanks - that' looks interesting. I'll check it out this evening.

**Comment by nmg196** [comment]
I'm really confused by both your comment and the instructions on the ESPHome page. Which files should be preserved or kept when copying the files into the ESPHome folder? If I let it overwrite the files with the same name then it doesn't even compile. 
I have opened an issue here: https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/issues/24

**Comment by absalom-muc** [comment]
I believe the issue was addressed, therefore closed. If there are further questions, please feel free to re-open it.
